# Generated by Django 5.0.2 on 2024-02-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='description',
            new_name='descripcion',
        ),
    ]
